# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='refresh_token',
        ),
    ]
