# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161231_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
