# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0011_cave_likes'),
        ('authentication', '0003_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_caves',
            field=models.ManyToManyField(to='caves.Cave'),
        ),
    ]
