# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0004_auto_20161231_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cave',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
