# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0005_auto_20161231_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
