# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0008_cave_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cave',
            old_name='public',
            new_name='is_public',
        ),
    ]
