# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0009_auto_20170104_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
