# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0010_cave_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='author_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
